### ISSUE TITLE
Update NPM package with refreshLongLivedToken method

### ISSUE THREAD

**Issue by alexwohlbruck** [loicnestler/instagram-basic-display#6]
Commit 528dc794bdf9178ba6baa504f614121383f68e78 added a function `refreshLongLivedToken`, but the NPM package does not include this function, it must have an older version of the codebase. Could you update the NPM package with this new function? I am trying to use it in my Heroku but the build pack won't find it if I add it manually.

**Comment by loicnestler** [comment]
Should be published!
Thank you for the issue!
